<?php

namespace Bordeux\Bundle\CronBundle\Controller\Admin;

use Sonata\AdminBundle\Controller\CRUDController;


/**
 * Class CronController
 * @author Chris Bednarczyk <chris@tourradar.com>
 * @package Bordeux\Bundle\CronBundle\Controller
 */
class CronController extends CRUDController
{
    public function showAction($id = null)
    {
        return parent::editAction($id); // TODO: Change the autogenerated stub
    }


}
