<?php

namespace Bordeux\Bundle\CronBundle\Controller\Admin;

use Sonata\AdminBundle\Controller\CRUDController;
use Symfony\Component\HttpFoundation\RedirectResponse;


/**
 * Class CronController
 * @author Chris Bednarczyk <chris@tourradar.com>
 * @package Bordeux\Bundle\CronBundle\Controller
 */
class CronController extends CRUDController
{

    /**
     * @param null $id
     * @return RedirectResponse
     * @author Chris Bednarczyk <chris@tourradar.com>
     */
    public function logsAction($id = null)
    {

        $id = $this->getRequest()->get($this->admin->getIdParameter());
        $url = $this->admin->generateUrl("bordeux.cron.sonata.cron.log.list", [
            'id' => $id
        ]);

        return new RedirectResponse($url);
    }


    public function showAction($id = null)
    {
        return parent::editAction($id); // TODO: Change the autogenerated stub
    }


}
