<?php

namespace Bordeux\Bundle\CronBundle\Repository;

/**
 * CronLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronLogRepository extends \Doctrine\ORM\EntityRepository
{
}
