<?php
namespace Bordeux\Bundle\CronBundle\Repository;

use Bordeux\Bundle\CronBundle\Entity\Cron;

/**
 * CronRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * @return Cron|null
     * @author Chris Bednarczyk <chris@tourradar.com>
     */
    public function getNextTask()
    {

        return $this->createQueryBuilder("t")
            ->andWhere("t.running = false")
            ->andWhere("t.nextRunDate IS NULL OR t.nextRunDate <= :now")
            ->andWhere("t.enabled = true")
            ->setParameter(
                ":now",
                new \DateTime()
            )
            ->setMaxResults(1)
            ->orderBy("t.lastRunDate", "ASC")
            ->getQuery()
            ->getOneOrNullResult();
    }
}
